import torch
import torch.nn as nn
import torch.nn.functional as F

class DifferentiableMemoryBuffer(nn.Module):
    """
    Bounded, differentiable structured KV memory buffer.
    Replaces hard LRU with an attention-weighted soft-overwrite slot mechanism.
    Incorporates positional decay to provide temporal bias (awareness of recency).
    """
    def __init__(self, d_model, num_slots=64):
        super().__init__()
        self.d_model = d_model
        self.num_slots = num_slots
        
        # In a differentiable slot setting, we can define fixed slot keys or learned ones
        self.slot_keys = nn.Parameter(torch.randn(1, num_slots, d_model) * 0.02)
        
        self.k_proj = nn.Linear(d_model, d_model, bias=False)
        self.v_proj = nn.Linear(d_model, d_model, bias=False)
        
        # Positional decay / Relative time encoding slope per head equivalent
        self.temporal_decay = nn.Parameter(torch.randn(1, num_slots))

    def forward(self, x_t, S_t, memory_state=None):
        """
        Write operation for a single time step.
        x_t: (batch, d_model)
        S_t: (batch, 1) Soft gating score from Event Detector
        memory_state: The current memory values buffer (batch, num_slots, d_model)
        
        Returns: updated_memory_state
        """
        b = x_t.size(0)
        
        if memory_state is None:
            memory_state = torch.zeros(b, self.num_slots, self.d_model, device=x_t.device)
            
        # Compute K, V for current token
        k_t = self.k_proj(x_t).unsqueeze(1) # (b, 1, d_model)
        v_t = self.v_proj(x_t).unsqueeze(1) # (b, 1, d_model)
        
        # Attention-weighted Overwrite mechanism (Slot Attention style)
        # Which slots should this token write to?
        # slot_keys: (1, num_slots, d_model), k_t: (b, 1, d_model)
        write_logits = torch.matmul(k_t, self.slot_keys.transpose(-1, -2)) / (self.d_model ** 0.5)
        # (b, 1, num_slots)
        write_weights = torch.softmax(write_logits, dim=-1)
        
        # Apply the event detector's soft gate (if S_t is low, we barely update memory)
        # write_updates: (b, num_slots, d_model)
        write_updates = (write_weights.transpose(-1, -2) * v_t) * S_t.unsqueeze(-1)
        
        # Update memory state smoothly. Old values are decayed softly or overwritten.
        # To maintain bounded magnitude, we do a convex combination
        decay_factor = 1.0 - (write_weights.transpose(-1, -2) * S_t.unsqueeze(-1))
        
        updated_memory_state = memory_state * decay_factor + write_updates
        
        return updated_memory_state

    def read_buffer(self, q_t, memory_state):
        """
        Read operation from the buffer.
        q_t: (batch, d_model) - Generated by the current token when a strike is triggered
        memory_state: (batch, num_slots, d_model) - The populated memory values
        """
        q_t = q_t.unsqueeze(1) # (b, 1, d_model)
        k_slots = self.slot_keys.expand(q_t.size(0), -1, -1) # (b, num_slots, d_model)
        
        # Standard attention over memory slots
        attn_logits = torch.matmul(q_t, k_slots.transpose(-1, -2)) / (self.d_model ** 0.5) # (b, 1, num_slots)
        
        # Apply temporal decay bias
        # Closer tokens (conceptually written later) might not map perfectly to slot index,
        # but if we enforce slot order as time order (or soft LRU), we apply temporal bias.
        # Alternatively, we just apply a learned bias per slot.
        attn_logits = attn_logits + self.temporal_decay.unsqueeze(1)
        
        attn_weights = torch.softmax(attn_logits, dim=-1)
        
        # Retrieve values
        read_out = torch.matmul(attn_weights, memory_state) # (b, 1, d_model)
        
        return read_out.squeeze(1)
